### ISSUE TITLE
デモサイトの初期データが、全文検索の対象に入っていない

### ISSUE THREAD

**Issue by kojisaiki** [enlighten-series/DomainDictionary#70]

**Comment by kojisaiki** [comment]
```
2018-07-01T06:19:38.698330+00:00 app[web.1]: 2018-07-01 06:19:38.698  INFO 4 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'webServlet' to [/h2-console/*]
2018-07-01T06:19:49.614286+00:00 app[web.1]: 2018-07-01 06:19:49.613  INFO 4 --- [           main] o.s.b.f.xml.XmlBeanDefinitionReader      : Loading XML bean definitions from class path resource [org/springframework/jdbc/support/sql-error-codes.xml]
2018-07-01T06:19:49.852408+00:00 app[web.1]: 2018-07-01 06:19:49.852  INFO 4 --- [           main] o.s.jdbc.support.SQLErrorCodesFactory    : SQLErrorCodes loaded: [DB2, Derby, H2, HSQL, Informix, MS-SQL, MySQL, Oracle, PostgreSQL, Sybase, Hana]
2018-07-01T06:19:50.718086+00:00 app[web.1]: デモデータのインデックス登録に失敗しました
2018-07-01T06:19:50.718957+00:00 app[web.1]: java.lang.NullPointerException
2018-07-01T06:19:50.719338+00:00 app[web.1]: 	at org.enlightenseries.DomainDictionary.infrastructure.config.LuceneDirectoryFactory.getInstance(LuceneDirectoryFactory.java:35)
2018-07-01T06:19:50.719445+00:00 app[web.1]: 	at org.enlightenseries.DomainDictionary.infrastructure.datasource.LuceneDatasource.existDomain(LuceneDatasource.java:134)
2018-07-01T06:19:50.719551+00:00 app[web.1]: 	at org.enlightenseries.DomainDictionary.infrastructure.datasource.LuceneDatasource.regist(LuceneDatasource.java:41)
2018-07-01T06:19:50.719642+00:00 app[web.1]: 	at org.enlightenseries.DomainDictionary.infrastructure.datasource.LuceneDatasource$$FastClassBySpringCGLIB$$1e7ff62e.invoke(<generated>)
2018-07-01T06:19:50.719733+00:00 app[web.1]: 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
2018-07-01T06:19:50.719824+00:00 app[web.1]: 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
2018-07-01T06:19:50.719915+00:00 app[web.1]: 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
2018-07-01T06:19:50.720015+00:00 app[web.1]: 	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
2018-07-01T06:19:50.720104+00:00 app[web.1]: 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
2018-07-01T06:19:50.720195+00:00 app[web.1]: 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
2018-07-01T06:19:50.720289+00:00 app[web.1]: 	at org.enlightenseries.DomainDictionary.infrastructure.datasource.LuceneDatasource$$EnhancerBySpringCGLIB$$242f3601.regist(<generated>)
2018-07-01T06:19:50.720386+00:00 app[web.1]: 	at org.enlightenseries.DomainDictionary.application.usecase.ApplicationMigration.insertDemoData(ApplicationMigration.java:195)
2018-07-01T06:19:50.720541+00:00 app[web.1]: 	at org.enlightenseries.DomainDictionary.application.usecase.ApplicationMigration.insertInitialData(ApplicationMigration.java:138)
2018-07-01T06:19:50.720636+00:00 app[web.1]: 	at org.enlightenseries.DomainDictionary.application.usecase.ApplicationMigration.initializeApplicationDatabase(ApplicationMigration.java:102)
2018-07-01T06:19:50.720726+00:00 app[web.1]: 	at org.enlightenseries.DomainDictionary.application.usecase.ApplicationMigration.checkApplicationMetadata(ApplicationMigration.java:95)
2018-07-01T06:19:50.720829+00:00 app[web.1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2018-07-01T06:19:50.720919+00:00 app[web.1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

**Comment by kojisaiki** [comment]
L34-36
```
      if (
        Arrays.stream(ApplicationContextProvider.getApplicationContext().getEnvironment().getActiveProfiles())
          .filter(s -> s.equals("prod"))
```

3択っぽいね

- ApplicationContextProvider
- getApplicationContext()
- getEnvironment()
